##### **PYTHON LIBRARIES**

In [31]:
from termcolor import colored
from functools import reduce
from datetime import datetime
import numpy as np 
import keyword

##### **ONE-LIER-FOR**

In [22]:
word = 'Python'
let_list = []
for i in word:
  let_list.append(i)
print(colored("\033[1m" + "We wrote with for loop: ", "blue"), let_list) 
l_list = [i for i in 'Python']
print(colored("\033[1m" + "We wrote just one-line: ", "blue"), l_list) 

state = 3
if state > 5:
  word = 'Apple'
else:
  word = 'Banana'
print(colored("\033[1m" + "We wrote  with if loop: ", "blue"), word) 
word = 'Apple' if state else 'Banane' if state > 5 else 'Strawberry'
print(colored("\033[1m" + "We rote just one-line: ", "blue"), word) 
square = lambda x: x**2
print(colored("\033[1m" + "take square using Lambda Function: ", "blue"), square(5)) 
numbers = [1, 2, 3, 4, 5, 6, 7]
num_of_squ = []
for num in numbers:
  num_of_squ.append(square(num))
print(colored("\033[1m" + "Num of Square: ", "blue"), num_of_squ) 
numbers = [1, 6, 3, 7, 10, 0]
print(colored("\033[1m" + "Numbers: ", "blue"), reduce(lambda x,y: x if x >y else y, numbers ))  # find max value
age = int(input('Your Age: '))
assert int(age) >=0, 'Your Age is not to be negative' # we can write an error

We wrote with for loop:  ['P', 'y', 't', 'h', 'o', 'n']
We wrote just one-line:  ['P', 'y', 't', 'h', 'o', 'n']
We wrote  with if loop:  Banana
We rote just one-line:  Apple
take square using Lambda Function:  25
Num of Square:  [1, 4, 9, 16, 25, 36, 49]
Numbers:  10
Your Age: 6


##### **GENERATORS and DECORATORS:**

In [25]:
def generator():
  i = 1
  print('First this code was working.')
  yield i

  i += 1
  print('After this code worked.')
  yield i
for val in generator():
  print(colored("\033[1m" + "Value in for loop: ", "blue"),val) 

First this code was working.
Value in for loop:  1
After this code worked.
Value in for loop:  2


In [30]:
def show_time(func):
  def wrapper():
    print(colored("\033[1m" + "Time is: ", "blue"), datetime.now().time()) 
    func()
  return wrapper
@show_time
def say_h():
  print(colored("\033[1m" + "Hi ", "blue"))
@show_time
def say_b():
  print(colored("\033[1m" + "Bye! ", "blue"))
say_h()
say_b()

Time is:  13:56:36.817721
Hi 
Time is:  13:56:36.817992
Bye! 


##### **NUMPY:**

In [37]:
a = np.array([10, 20, 30, 40, 50, 60])
print(colored("\033[1m" + "Name of A Array is: ", "blue"), a) 
print(colored("\033[1m" + "Shape of A Array is: ", "blue"), a.shape) 
print(colored("\033[1m" + "Sin of A Array is: ", "blue"), np.sin(a)) 
print(colored("\033[1m" + "Cos of A Array is: ", "blue"), np.cos(a)) 
print(colored("\033[1m" + "Log of A Array is: ", "blue"), np.log(a)) 
print(colored("\033[1m" + "Exponenciel of A Array is: ", "blue"), np.exp(a)) 
print(colored("\033[1m" + "Max Value in A Array is: ", "blue"), np.max(a)) 
print(colored("\033[1m" + "Mean in A Array is: ", "blue"), np.mean(a))
print(colored("\033[1m" + "Median in A Array is: ", "blue"), np.median(a)) 
print(colored("\033[1m" + "Standar dev. in A Array is: ", "blue"), np.std(a)) 
print(colored("\033[1m" + "Type of A Array is: ", "blue"), type(a)) 
print(colored("\033[1m" + "TName of A Array is: ", "blue"), a) 

Name of A Array is:  [10 20 30 40 50 60]
Shape of A Array is:  (6,)
Sin of A Array is:  [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062]
Cos of A Array is:  [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603 -0.95241298]
Log of A Array is:  [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456]
Exponenciel of A Array is:  [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21 1.14200739e+26]
Max Value in A Array is:  60
Mean in A Array is:  35.0
Median in A Array is:  35.0
Standar dev. in A Array is:  17.07825127659933
Type of A Array is:  <class 'numpy.ndarray'>
TName of A Array is:  [10 20 30 40 50 60]


In [55]:
zeros = np.zeros((3,10))
print(colored("\033[1m" + "Zero Array is: ", "blue"), '\n',  zeros) 
ones = np.ones((3,10))
print(colored("\033[1m" + "One Array is: ", "blue"), '\n',  ones) 
full = np.full((3,3),5)
print(colored("\033[1m" + "Full Array is: ", "blue"), '\n',  full) 
eye = np.eye(5)
print(colored("\033[1m" + "Eye Array is: ", "blue"), '\n',  eye) 
print(colored("\033[1m" + "Arange Array is: ", "blue"), '\n',  np.arange(7)) 
print(colored("\033[1m" + "Different Arange Array is: ", "blue"), '\n',  np.arange(0, 10, 2))
print(colored("\033[1m" + "Random Array is: ", "blue"), '\n',  np.random.random((3,3))) 
print(colored("\033[1m" + "Random Integer Array is: ", "blue"), '\n',  np.random.randint(20, size=(5,5))) 
arr1 = np.random.randint(20, size=(5,5))
print(colored("\033[1m" + "Select value from Random Integer Array: ", "blue"),  arr1[2,1]) 
print(colored("\033[1m" + "Where is the value of 11: ", "blue"),  np.where(arr1==11)) 

Zero Array is:  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
One Array is:  
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Full Array is:  
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Eye Array is:  
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange Array is:  
 [0 1 2 3 4 5 6]
Different Arange Array is:  
 [0 2 4 6 8]
Random Array is:  
 [[0.42459327 0.34556858 0.62239754]
 [0.64928538 0.74654414 0.69545877]
 [0.28926225 0.21537234 0.44515643]]
Random Integer Array is:  
 [[18  3 13  6  2]
 [15  7 15  0 13]
 [ 0  7 11  2 13]
 [ 8 19  2  6 15]
 [ 5 17 15  9 18]]
Select value from Random Integer Array:  4
Where is the value of 11:  (array([2, 4, 4]), array([2, 0, 3]))


In [68]:
a = np.array([[1,2,3],[4,5,6]])
print(colored("\033[1m" + "A Array is: ", "blue"), '\n', a)
print(colored("\033[1m" + "A Array Shape is: ", "blue"), a.shape)
b = np.array([[7,8,9],[10,11,12]])
print(colored("\033[1m" + "B Array is: ", "blue"), '\n', b)
print(colored("\033[1m" + "B Array Shape is: ", "blue"), b.shape)
axb = np.dot(a,(b.T))
print(colored("\033[1m" + "AxB give us new array 2x2: ", "blue"), '\n', axb)
print(colored("\033[1m" + "AxB Array Shape is: ", "blue"), axb.shape)

A Array is:  
 [[1 2 3]
 [4 5 6]]
A Array Shape is:  (2, 3)
B Array is:  
 [[ 7  8  9]
 [10 11 12]]
B Array Shape is:  (2, 3)
AxB give us new array 2x2:  
 [[ 50  68]
 [122 167]]
AxB Array Shape is:  (2, 2)
